spring:
  application:
    name: Xindong-tranxact-backend
  datasource:
    url: jdbc:mysql://localhost:3306/xindong_tranxact
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: localhost
      port: 6379
  cache:
    type: none
    redis:
      time-to-live: 60000
  security:
    jwt:
      key: xa_key
      expires: 1
server:
  port: 8100

springdoc:
  swagger-ui:
    path: dev/APIDocs.html
    enabled: true
    csrf:
      enabled: true

  api-docs:
    enabled: true


  packages-to-scan: neu.xindong.xact.controller
  enable-data-rest: true